const CONFIG = {
    TIMER_DURATION: 60*3, 
    THEME: "classic",
    ENABLE_SOUND: true,
    IS_FLIPPED: false,
    THEME_KEY: "theme",
    ENABLE_SOUND_KEY: "enableSound", 
    TIMER_DURATION_KEY: "timerDuration",
    IS_FLIPPED_KEY: "isFlipped",
    CHESS_GAME_KEY: "chessGame",
    START_FEN: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
    CLEAR_FEN: "8/8/8/8/8/8/8/8 w KQkq - 0 1",
    FINAL_FEN_KEY: "finalFen",
    CHECKMATE_MESSAGE: "Wins by Checkmate!",
    WHITE: 'w',
    BLACK: 'b', 
    CHESS_PIECE: "chessPiece",
    ERASER: "eraser",
  };
  
  export default CONFIG;

export const startPosBoard = [
    [
      {id: "a8", piece: {type: 'r', color: 'b'}}, 
      {id: "b8", piece: {type: 'n', color: 'b'}}, 
      {id: "c8", piece: {type: 'b', color: 'b'}}, 
      {id: "d8", piece: {type: 'q', color: 'b'}}, 
      {id: "e8", piece: {type: 'k', color: 'b'}}, 
      {id: "f8", piece: {type: 'b', color: 'b'}}, 
      {id: "g8", piece: {type: 'n', color: 'b'}}, 
      {id: "h8", piece: {type: 'r', color: 'b'}}
    ],
    [
      {id: "a7", piece: {type: 'p', color: 'b'}},
      {id: "b7", piece: {type: 'p', color: 'b'}},
      {id: "c7", piece: {type: 'p', color: 'b'}},
      {id: "d7", piece: {type: 'p', color: 'b'}},
      {id: "e7", piece: {type: 'p', color: 'b'}},
      {id: "f7", piece: {type: 'p', color: 'b'}},
      {id: "g7", piece: {type: 'p', color: 'b'}},
      {id: "h7", piece: {type: 'p', color: 'b'}},
    ],
    [
      {id: 'a6', piece: null},
      {id: 'b6', piece: null},
      {id: 'c6', piece: null},
      {id: 'd6', piece: null},
      {id: 'e6', piece: null},
      {id: 'f6', piece: null},
      {id: 'g6', piece: null},
      {id: 'h6', piece: null},
    ],
    [
      {id: 'a5', piece: null},
      {id: 'b5', piece: null},
      {id: 'c5', piece: null},
      {id: 'd5', piece: null},
      {id: 'e5', piece: null},
      {id: 'f5', piece: null},
      {id: 'g5', piece: null},
      {id: 'h5', piece: null},
    ],
    [
      {id: 'a4', piece: null},
      {id: 'b4', piece: null},
      {id: 'c4', piece: null},
      {id: 'd4', piece: null},
      {id: 'e4', piece: null},
      {id: 'f4', piece: null},
      {id: 'g4', piece: null},
      {id: 'h4', piece: null},
    ],
    [
      {id: 'a3', piece: null},
      {id: 'b3', piece: null},
      {id: 'c3', piece: null},
      {id: 'd3', piece: null},
      {id: 'e3', piece: null},
      {id: 'f3', piece: null},
      {id: 'g3', piece: null},
      {id: 'h3', piece: null},
    ],
    [
      {id: 'a2', piece: {type: 'p', color: 'w'}},
      {id: 'b2', piece: {type: 'p', color: 'w'}},
      {id: 'c2', piece: {type: 'p', color: 'w'}},
      {id: 'd2', piece: {type: 'p', color: 'w'}},
      {id: 'e2', piece: {type: 'p', color: 'w'}},
      {id: 'f2', piece: {type: 'p', color: 'w'}},
      {id: 'g2', piece: {type: 'p', color: 'w'}},
      {id: 'h2', piece: {type: 'p', color: 'w'}} 
    ],
    [
      {id: 'a1', piece: {type: 'r', color: 'w'}},
      {id: 'b1', piece: {type: 'n', color: 'w'}},
      {id: 'c1', piece: {type: 'b', color: 'w'}},
      {id: 'd1', piece: {type: 'q', color: 'w'}},
      {id: 'e1', piece: {type: 'k', color: 'w'}},
      {id: 'f1', piece: {type: 'b', color: 'w'}},
      {id: 'g1', piece: {type: 'n', color: 'w'}},
      {id: 'h1', piece: {type: 'r', color: 'w'}}
    ],
  ]

export const clearBoard = [
    [
      {id: "a8", piece: null}, 
      {id: "b8", piece: null}, 
      {id: "c8", piece: null}, 
      {id: "d8", piece: null}, 
      {id: "e8", piece: null}, 
      {id: "f8", piece: null}, 
      {id: "g8", piece: null}, 
      {id: "h8", piece: null}
    ],
    [
      {id: "a7", piece: null},
      {id: "b7", piece: null},
      {id: "c7", piece: null},
      {id: "d7", piece: null},
      {id: "e7", piece: null},
      {id: "f7", piece: null},
      {id: "g7", piece: null},
      {id: "h7", piece: null},
    ],
    [
      {id: 'a6', piece: null},
      {id: 'b6', piece: null},
      {id: 'c6', piece: null},
      {id: 'd6', piece: null},
      {id: 'e6', piece: null},
      {id: 'f6', piece: null},
      {id: 'g6', piece: null},
      {id: 'h6', piece: null},
    ],
    [
      {id: 'a5', piece: null},
      {id: 'b5', piece: null},
      {id: 'c5', piece: null},
      {id: 'd5', piece: null},
      {id: 'e5', piece: null},
      {id: 'f5', piece: null},
      {id: 'g5', piece: null},
      {id: 'h5', piece: null},
    ],
    [
      {id: 'a4', piece: null},
      {id: 'b4', piece: null},
      {id: 'c4', piece: null},
      {id: 'd4', piece: null},
      {id: 'e4', piece: null},
      {id: 'f4', piece: null},
      {id: 'g4', piece: null},
      {id: 'h4', piece: null},
    ],
    [
      {id: 'a3', piece: null},
      {id: 'b3', piece: null},
      {id: 'c3', piece: null},
      {id: 'd3', piece: null},
      {id: 'e3', piece: null},
      {id: 'f3', piece: null},
      {id: 'g3', piece: null},
      {id: 'h3', piece: null},
    ],
    [
      {id: 'a2', piece: null},
      {id: 'b2', piece: null},
      {id: 'c2', piece: null},
      {id: 'd2', piece: null},
      {id: 'e2', piece: null},
      {id: 'f2', piece: null},
      {id: 'g2', piece: null},
      {id: 'h2', piece: null} 
    ],
    [
      {id: 'a1', piece: null},
      {id: 'b1', piece: null},
      {id: 'c1', piece: null},
      {id: 'd1', piece: null},
      {id: 'e1', piece: null},
      {id: 'f1', piece: null},
      {id: 'g1', piece: null},
      {id: 'h1', piece: null}
    ],
  ]
